# Generated by Django 3.1.7 on 2021-03-23 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_auto_20210323_1204'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='difftime',
        ),
    ]
